### PR TITLE
Add cask sources API

### PR DESCRIPTION
**Pull request by Rylan12**
This PR adds a new `/api/cask-source/foo.rb` API for getting the text contents of a cask file.

This will eventually be used to allow casks to be installed without needing `homebrew/cask` to be tapped.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Why the text source? Why not json like the other APIs?

**Comment by Rylan12** [comment]
For formulae, we still technically install from the formula file. But, instead of hosting the file directly here, we extract it from the bottle archive itself. So, the bottle JSON only contains URLs and checksums for the formula's bottles (and the formula dependencies' bottles). Casks don't really have an equivalent of a bottle so there's no way to get the cask file "from" anything aside from the API directly. Does that make sense?

We could also get it directly from GitHub (i.e. [here](https://raw.githubusercontent.com/Homebrew/homebrew-cask/master/Casks/docker.rb)) but Mike (not to throw him under the bus here) seemed to think it was more performant to host here. The other benefit is that changes are in sync with the other formulae.brew.sh changes. So, there won't be a situation where `/api/versions-cask.json` (which I still have to add) shows a different version than the latest cask file on GitHub.

**Review by MikeMcQuaid — APPROVED** [review]
Makes sense, thanks again @Rylan12!

**Comment by Rylan12** [comment]
I will add documentation for this along with the other new APIs in #486 once we're ready to start documenting this stuff.

I will plan on starting to work more closely on the cask stuff in the next week or so (I've been out of town again so I haven't had as much time to finish up this stuff as before).

**Pull request merged**
