### PR TITLE
docs: stabilize bottle API responses

### PR DESCRIPTION
**Pull request by skyzh**
This PR updates sample API response in the API docs. It might include some changes in https://github.com/Homebrew/formulae.brew.sh/pull/486. Maybe we should get that merged before this PR gets merged.

Regarding the previous discussions about making a Homebrew mirror https://github.com/Homebrew/discussions/discussions/1906, this is our first step to make mirroring easier by stabilizing some fields in JSON API.

Mirror tools made by mirror maintainers from Linux user groups in China require specific fields from the JSON API for the mirroring tools to work. Specifically, they need the following structures:

* JSON API response should at least contains the following structure (or fields):
    ```
    Response = [Formula*]
    Formula = { name, Versions, Bottle, revision }
    Bottle = BottleStable?
    BottleStable = { rebuild, Files }
    Versions = { stable?, bottle }
    Files = { [system_arch]: { url, sha256 } }
    ```
* The `url` field should always contain a blob file on `ghcr.io`, like `https://ghcr.io/v2/homebrew/core/wget/blobs/sha256:ab03f58f6d9a4018b1b0bfd53e5b797fcd90b86b1d60b20948de499ec4d4c6b4`.

Reference: [USTCLUG's bottles-json parser](https://github.com/ustclug/ustcmirror-images/blob/master/homebrew-bottles/bottles-json/src/main.rs), [SJTUG's mirror-clone](https://github.com/sjtug/mirror-clone/blob/master/src/homebrew.rs)

This PR just serves as a hint on how mirror tools use Homebrew APIs. If any contributor needs to update the response structure of Homebrew APIs, this PR would make them aware that changing some specific field will break mirror tools in the community unintentionally.

cc @taoky @shankerwangmiao does this look okay to you?

And cc @MikeMcQuaid for review, many thanks!

### CODE REVIEW

**Review by Rylan12 — APPROVED** [review]
Good call, thanks @skyzh!

Thinking about keeping this updated in the future: because changes to this output are made in Homebrew/brew, it's much less likely for contributors to remember to update the docs here. You could, if you wanted, use `brew info --json` (and its various invocations) as the main point of reference moving forward because that's more accurate to this output in terms of the fields present. It's not perfect, though, because the top-level format (i.e. is it an array or an object) doesn't quite match here, and you need to use `--json=v2` for casks.

I wonder if we can automatically update this every time it changes. I'll look into it and maybe do that in #486 (which is intentionally blocked at the moment). I'm thinking something like how we can access `{{ site.taps.core.repo }}` on this page. Not a blocker, here, just mentioning it in case anyone has thoughts.

**Comment by Rylan12** [comment]
Thanks, @skyzh!

Just so you know, I've opened #523 which, if merged, will automatically update these samples which will keep them up to date (and mean we won't need PRs like this every few months when something changes).

**Comment by Rylan12** [comment]
Just an update: #523 has been merged so hopefully, this won't be a problem in the future. 🤞 Plus, in addition to updating documentation automatically, we're probably going to add additional checks to [make sure that we don't make backward-incompatible changes accidentally in the future](https://github.com/Homebrew/formulae.brew.sh/pull/523#issuecomment-892064105). Not sure the timeline for that, yet, but keep your eyes peeled if you're curious.

**Comment by skyzh** [comment]
> Just an update: #523 has been merged so hopefully, this won't be a problem in the future. 🤞 Plus, in addition to updating documentation automatically, we're probably going to add additional checks to [make sure that we don't make backward-incompatible changes accidentally in the future](https://github.com/Homebrew/formulae.brew.sh/pull/523#issuecomment-892064105). Not sure the timeline for that, yet, but keep your eyes peeled if you're curious.

Thanks a lot! I'll keep an eye on that.

**Pull request merged**
