### PR TITLE
set custom link

### PR DESCRIPTION
**Pull request by ldct**
Will kick in after https://github.com/Homebrew/brew.sh/pull/222 lands

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
@ldct It should be possible to use https://help.github.com/articles/repository-metadata-on-github-pages/ rather than hardcoding this. Thoughts?

**Comment by ldct** [comment]
I think the problem would be that the site currently hosted on brew.sh, which is running code from the repo Homebrew/brew.sh, wants to point to the repo Homebrew/brew

**Comment by MikeMcQuaid** [comment]
Could use it for formulae.brew.sh (and docs.brew.sh) though, no?

**Comment by ldct** [comment]
yes, but you'd need to override it for brew.sh

**Comment by ldct** [comment]
also it's not clear to me which repo https://docs.brew.sh/ actually wants to point users to

**Comment by MikeMcQuaid** [comment]
> also it's not clear to me which repo https://docs.brew.sh/ actually wants to point users to

I've made it link to the individual pages for easy editing.

**Comment by MikeMcQuaid** [comment]
Thanks again @ldct!

**Pull request merged**
