### PR TITLE
Add initial cask json files.

### PR DESCRIPTION
**Pull request by cmbernard333**
Add the initial set of Cask Json files

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Will hold off merging these until we have `homebrew-cask` repo wired up so they are updated.

**Comment by MikeMcQuaid** [comment]
@cmbernard333 If you rebase this on `master` it should be easier to review/test any last bits.

**Comment by MikeMcQuaid** [comment]
@cmbernard333 Also I think you could generate/commit the `cask` directory and wire it up in the HTML too.

**Comment by cmbernard333** [comment]
@cmbernard333 it looks like there is an initial commit of the cask JSON data already. I'll pull in the latest stuff from master and see what I can identify.

**Comment by MikeMcQuaid** [comment]
@cmbernard333 Yeh, I'd suggest just rebasing this on `master` (if there's anything left after that!).

**Comment by cmbernard333** [comment]
@MikeMcQuaid it looks like #114 is going to address the HTML. I am going to close this PR.

**Comment by MikeMcQuaid** [comment]
@cmbernard333 Cool, thanks. Do you think there's anything else to do after #114?

**Pull request closed without merging**
