### PR TITLE
Automatically generate API samples

### PR DESCRIPTION
**Pull request by Rylan12**
This PR extracts the sample API results from [the docs](https://formulae.brew.sh/docs/api/) to their own files in `_includes` which are then inserted into the main doc file. This means that the `docs/api.md` file is much cleaner, plus it allows us to automatically generate and update these samples.

This PR also sets up automatic generation of these samples. This actually uses the API results from the _previous_ generation, though. So if a change to the API is made, it will take two generations (usually two hours) for it to populate in these files. I did this only because it was much easier to do (although suggestions are definitely welcome), and I don't think it will be much of an issue (especially since who knows when the last time this was updated was).

Once this is merged, https://github.com/Homebrew/formulae.brew.sh/pull/521 won't be needed. If that PR is merged first (which I'm anticipating will be the case), I'll handle the conflicts and rebase this one. This PR shouldn't block that one because updating the super-old docs is more important than setting up the auto-updates.

### CODE REVIEW

**Review by MikeMcQuaid — APPROVED** [review]
This is 💖, wonderful work @Rylan12. A useful follow-up PR I could see would be notifying us if we accidentally break the API i.e. by removing or changing the datatype of a field.

**Comment by Rylan12** [comment]
Agreed. Any suggestions for how to do that? The changes breaking changes would be in Homebrew/brew. Think it's worth just having a test that fails if `Formula#to_hash` or the cask/analytics equivalent differs? Not exactly sure yet the best way for that to happen but it should be doable. Alternative if a test isn't good is to have @BrewTestBot post an issue if things break

**Comment by MikeMcQuaid** [comment]
> The changes breaking changes would be in Homebrew/brew. Think it's worth just having a test that fails if `Formula#to_hash` or the cask/analytics equivalent differs?

Yeh, I think so. Hardcode the format in Homebrew/brew with some sort of validation? JSON schema is quite nice for this sort of thing; we could consider publishing the schema in formulae.brew.sh and validating against it in Homebrew/brew?

**Comment by SMillerDev** [comment]
I was actually thinking of setting that up exactly like that. Host the schema somewhere and add a check step in brew CI.

**Comment by MikeMcQuaid** [comment]
`github_packages.rb` already does some JSON schema validation so may be a useful place to rear to.

**Comment by Rylan12** [comment]
> I was actually thinking of setting that up exactly like that. Host the schema somewhere and add a check step in brew CI.

Feel free to work on this if you'd like. If you don't I'll try to take a look but probably won't be for a bit. Want to finish the json stuff first.

**Pull request merged**
