### PR TITLE
Remove cask-source, bottle and versions APIs

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
These are no longer needed after https://github.com/Homebrew/brew/pull/14439 and https://github.com/Homebrew/brew/pull/14500 are merged and in a stable tag.

### CODE REVIEW

**Review by Rylan12 — APPROVED** [review]
Thanks! I need to double-check this but I think we can also remove the `versions-casks` and `versions-formulae` APIs

**Comment by MikeMcQuaid** [comment]
> but I think we can also remove the `versions-casks` and `versions-formulae` APIs

@Rylan12 Good call, done here and in https://github.com/Homebrew/brew/pull/14500.

**Review by Rylan12 — APPROVED** [review]
Thanks!

**Review by Rylan12 — APPROVED** [review]
Thanks!

**Review by Rylan12 — APPROVED** [review]

**Review by Rylan12 — APPROVED** [review]

**Pull request merged**
