### PR TITLE
add cask install analytics

### PR DESCRIPTION
**Pull request by brianmorton**
https://github.com/Homebrew/formulae.brew.sh/issues/13

edit: also requires https://github.com/Homebrew/homebrew-formula-analytics/pull/59 to be implemented in order to generate new/updated analytics

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
> edit: also requires [Homebrew/homebrew-formula-analytics#59](https://github.com/Homebrew/homebrew-formula-analytics/pull/59) to be implemented in order to generate new/updated analytics

@brianmorton You also need to update https://github.com/Homebrew/formulae.brew.sh/blob/6d52e55f349087ccd300268831324f464b54e574/Rakefile#L49-L78. My suggestion would be to do that in a separate PR which can be merged, let it generate the JSON itself and remove the JSON you've committed to this PR.

**Comment by MikeMcQuaid** [comment]
@brianmorton Any news here? Would you consider adding @cmbernard333 to have rights to your fork so they can pick up where you've left off?

**Comment by brianmorton** [comment]
I will look at this again tomorrow... sorry I thought I was good and was just waiting for the PR to be merged - must have dismissed the notification on this thread somewhere along the way.

**Comment by brianmorton** [comment]
As requested: https://github.com/Homebrew/formulae.brew.sh/pull/94

**Comment by MikeMcQuaid** [comment]
Houston, we have cask data: https://github.com/Homebrew/formulae.brew.sh/tree/master/_data/analytics/cask-install

**Comment by MikeMcQuaid** [comment]
Thanks @brianmorton!

**Pull request merged**
