### PR TITLE
Add versions API

### PR DESCRIPTION
**Pull request by Rylan12**
This PR adds a new versions API. This is a JSON file that is structured so that each formula name maps to an array containing the latest version and revision. Here's an example (the real files include all formulae in homebrew/core).

```json
{
  "hello":{"version":"2.10","revision":0},
  "minimesos":{"version":"0.13.0","revision":1}
}
```

This PR will allow for `brew outdated` to query this file which takes much much less time to process than the existing https://formulae.brew.sh/api/formula.json file (or the individual formula files).

These files would be available at https://formulae.brew.sh/api/versions.json and https://formulae.brew.sh/api/versions-linux.json.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Why not an object? This array location logic seems like too much magic to me.

**Comment by Rylan12** [comment]
Yeah, good point. No real reason other than that it requires having `"version"` and `"revision"` labels but that's probably a good idea.

**Comment by SMillerDev** [comment]
Can this also be done for casks?

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
Great work here @Rylan12.

@SMillerDev eventually: yes but @Rylan12 isn't working (yet?) on the installing casks without homebrew-cask tapped.

**Comment by Rylan12** [comment]
Think it's worth adding this info for casks now? It wouldn't be used anywhere (yet) so I figured I'd stick with just formulae for now. But, maybe it's worth thinking about adding it now.

Right now, I have `/api/versions.json` and `/api/versions-linux.json`, so it would seem reasonable for the cask equivalent to be `/api/versions-cask.json`. Does that seem appropriate? Alternatively, I could rename the "default" to `/api/versions-formula.json` or something like that to be consistent. I figure eventually all of the `-linux` stuff will be removed, so we'll just be left with `formula` and `cask` everywhere without any `-linux` suffixes, so should we be consistent with that here?

**Comment by SMillerDev** [comment]
> Think it's worth adding this info for casks now? It wouldn't be used anywhere (yet) so I figured I'd stick with just formulae for now. But, maybe it's worth thinking about adding it now.

Yeah, seems like a low effort addition, that's why I asked.

I think `versions-formulae`, `versions-casks`, `versions-linux` is a good division. You could likely even get away without the linux API since it's getting merged right this moment.

**Comment by Rylan12** [comment]
👍 Just pushed a commit that changes `/api/versions.json` to `/api/versions-formulae.json` and adds `/api/versions-casks.json`.

For the cask versions file, I chose to structure it the same way as the formulae versions file minus the `revision` field. This could be reduced to just a single top-level object that contains `"token":"version"` mappings, but for consistency, it's structured like this for now:

```json
{
  "0-ad":{"version":"0.0.24b-alpha"},
  "010-editor":{"version":"11.0.1"},
}
```

For now, I'd like to keep the `api/versions-linux.json` because it will be used in Homebrew/brew and we're not _quite_ there yet where it can be removed.

**Review by SMillerDev — APPROVED** [review]

**Comment by SMillerDev** [comment]
Good call to keep the same structure for casks, LGTM now

**Pull request merged**
